#!/bin/bash
curl -X POST http://localhost:8999/receive_json \
-H "Content-Type: application/json" \
-d '{
    "simbox_name": "PC",
    "psms_name": "PSMS",
    "status": "IDLE",
    "senders": {
        "1": {
            "status": "IDLE",
            "error": "",
            "error_code": 0,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 1,
            "ts": 1740325944.1715376,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56932301460",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068535261",
                "imsi": "730011455845361",
                "registration_status": "5",
                "operator": "Movistar entel",
                "rat": "GSM",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "OK",
                "sms_result": "",
                "gps_location":"32.0424366,34.8474245,44.8"
            }
        },
        "2": {
            "status": "IDLE",
            "error": "Modem is not connected: 0 (Not registered. ME is not currently searching a new operator to register to)",
            "error_code": -22,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 2,
            "ts": 1740325944.1715546,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068550294",
                "imsi": "730011455845363",
                "registration_status": "0",
                "operator": "",
                "rat": "",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "",
                "sms_result": "",
                "gps_location":"32.3522435,34.822235,45.2"
            }
        },
        "3": {
            "status": "IDLE",
            "error": "Modem is not connected: 0 (Not registered. ME is not currently searching a new operator to register to)",
            "error_code": -22,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 3,
            "ts": 1740325944.1715624,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068538224",
                "imsi": "730011455845360",
                "registration_status": "0",
                "operator": "",
                "rat": "",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "",
                "sms_result": "",
                "gps_location":"32.094495,34.842424717,45.1"
            }
        },
        "4": {
            "status": "IDLE",
            "error": "Modem is not connected: 0 (Not registered. ME is not currently searching a new operator to register to)",
            "error_code": -22,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 4,
            "ts": 1740325944.1715686,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068550278",
                "imsi": "730011455845319",
                "registration_status": "0",
                "operator": "",
                "rat": "",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "",
                "sms_result": "",
                "gps_location":"32.098559,34.847792,45.5"
            }
        },
        "5": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 5,
            "ts": 1740325944.1715758,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56983688626",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068550310",
                "imsi": "730029980666184",
                "registration_status": "1",
                "operator": "movistar movistar",
                "rat": "GSM",
                "arfcn": "688",
                "bsic": "41",
                "psc": "",
                "pci": "",
                "mcc": "730",
                "mnc": "02",
                "lac": "29825",
                "cell_id": "8666",
                "rssi": "-67",
                "snr": "0",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.098622,34.847867,45.3"
            }
        },
        "6": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 6,
            "ts": 1740325944.1715827,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56983683563",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068619552",
                "imsi": "730029980666181",
                "registration_status": "1",
                "operator": "movistar movistar",
                "rat": "GSM",
                "arfcn": "688",
                "bsic": "41",
                "psc": "",
                "pci": "",
                "mcc": "730",
                "mnc": "02",
                "lac": "29825",
                "cell_id": "8666",
                "rssi": "-70",
                "snr": "0",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.098686,34.847942,45.1"
            }
        },
        "7": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 7,
            "ts": 1740325944.1715899,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56983684849",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068551284",
                "imsi": "730029980666182",
                "registration_status": "1",
                "operator": "movistar movistar",
                "rat": "GSM",
                "arfcn": "688",
                "bsic": "41",
                "psc": "",
                "pci": "",
                "mcc": "730",
                "mnc": "02",
                "lac": "29825",
                "cell_id": "8666",
                "rssi": "-68",
                "snr": "0",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.098750,34.848017,44.8"
            }
        },
        "8": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 8,
            "ts": 1740325944.1715963,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56983690885",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068548645",
                "imsi": "730029980666186",
                "registration_status": "1",
                "operator": "movistar movistar",
                "rat": "GSM",
                "arfcn": "688",
                "bsic": "41",
                "psc": "",
                "pci": "",
                "mcc": "730",
                "mnc": "02",
                "lac": "29825",
                "cell_id": "8666",
                "rssi": "-68",
                "snr": "0",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.098813,34.848092,44.9"
            }
        },
        "9": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 9,
            "ts": 1740325944.1716027,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56984900729",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068619586",
                "imsi": "730030552170787",
                "registration_status": "5",
                "operator": "Movistar Claro",
                "rat": "GSM",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.098877,34.848167,44.9"

            }
        },
        "10": {
            "status": "ERROR",
            "error": "Failed to receive expected response to command ATD+56962515275;: ERROR",
            "error_code": -10,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 10,
            "ts": 1740325944.1716092,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068548769",
                "imsi": "",
                "registration_status": "",
                "operator": "",
                "rat": "",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "failed_atd",
                "sms_result": "",
                "gps_location":"32.098941,34.848242,44.9"
            }
        },
        "11": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 11,
            "ts": 1740325944.1716156,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068540352",
                "imsi": "730030552170788",
                "registration_status": "5",
                "operator": "Movistar Claro",
                "rat": "LTE",
                "arfcn": "2536",
                "bsic": "",
                "psc": "",
                "pci": "103",
                "mcc": "730",
                "mnc": "03",
                "lac": "1003",
                "cell_id": "3584",
                "rssi": "-55",
                "snr": "-7",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.099004,34.848317,44.8"
            }
        },
        "12": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 12,
            "ts": 1740325944.1716228,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56986147581",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068548850",
                "imsi": "730030552170786",
                "registration_status": "1",
                "operator": "Claro Claro",
                "rat": "GSM",
                "arfcn": "250",
                "bsic": "12",
                "psc": "",
                "pci": "",
                "mcc": "730",
                "mnc": "03",
                "lac": "1415",
                "cell_id": "38624",
                "rssi": "-72",
                "snr": "0",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.099068,34.848392,44.3"
            }
        },
        "13": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 13,
            "ts": 1740325944.171629,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56929088250",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068550203",
                "imsi": "730090077006090",
                "registration_status": "1",
                "operator": "WOM WOM",
                "rat": "LTE",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.099131,34.848467,44.2"
            }
        },
        "14": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 14,
            "ts": 1740325944.1716352,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068550492",
                "imsi": "730090077006074",
                "registration_status": "1",
                "operator": "WOM WOM",
                "rat": "LTE",
                "arfcn": "",
                "bsic": "",
                "psc": "",
                "pci": "",
                "mcc": "",
                "mnc": "",
                "lac": "",
                "cell_id": "",
                "rssi": "",
                "snr": "",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.099195,34.848542,44.1"
            }
        },
        "15": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 15,
            "ts": 1740325944.171641,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56929828696",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068548686",
                "imsi": "730090077006094",
                "registration_status": "1",
                "operator": "WOM WOM",
                "rat": "LTE",
                "arfcn": "9260",
                "bsic": "",
                "psc": "",
                "pci": "10",
                "mcc": "730",
                "mnc": "09",
                "lac": "1353",
                "cell_id": "23315782",
                "rssi": "-59",
                "snr": "-20",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.099259,34.848617,44.4"
            }
        },
        "16": {
            "status": "IDLE",
            "error": "Timeout to receive expected response [.CONNECT., .BUSY., .NO CARRIER., .NO ANSWER.] to command Dial",
            "error_code": -12,
            "msisdn": "+56962515275",
            "sent": 0,
            "modem_index_i2c": 16,
            "ts": 1740325944.1716475,
            "network": "auto",
            "use_call": 1,
            "use_sms": 0,
            "is_loopback_msisdn": 0,
            "modem_msisdn": "+56935630283",
            "survey_results": {
                "model": "Quectel EG25",
                "imei": "867929068535006",
                "imsi": "730011455845362",
                "registration_status": "5",
                "operator": "Movistar entel",
                "rat": "GSM",
                "arfcn": "688",
                "bsic": "41",
                "psc": "",
                "pci": "",
                "mcc": "730",
                "mnc": "02",
                "lac": "29825",
                "cell_id": "8666",
                "rssi": "-69",
                "snr": "0",
                "call_result": "failed_timeout",
                "sms_result": "",
                "gps_location":"32.099322,34.848692,44.9"
            }
        }
    }
}'
